In [ ]:
# 1. State the Hypotheses
#Null Hypothesis (H₀): There is no association between device type (Smart Thermostat or Smart Light) and customer satisfaction level. They are independent.

#Alternative Hypothesis (H₁): There is an association between device type and customer satisfaction level. They are not independent.



In [1]:
import numpy as np
import scipy.stats as stats

# Observed frequencies
observed = np.array([
    [50, 70],
    [80, 100],
    [60, 90],
    [30, 50],
    [20, 50]
])

# Perform Chi-Square test
chi2_stat, p_value, dof, expected = stats.chi2_contingency(observed)

# Output results
print("Chi-Square Statistic:", round(chi2_stat, 2))
print("Degrees of Freedom:", dof)
print("P-Value:", round(p_value, 4))
print("\nExpected Frequencies:\n", expected)


Chi-Square Statistic: 5.64
Degrees of Freedom: 4
P-Value: 0.2278

Expected Frequencies:
 [[ 48.  72.]
 [ 72. 108.]
 [ 60.  90.]
 [ 32.  48.]
 [ 28.  42.]]


In [2]:
"""
Chi-Square Test of Independence
Assignment: Association between Device Type and Customer Satisfaction
Author: [Your Name]
Date: [Current Date]
"""

import numpy as np
import scipy.stats as stats

# -------------------------------
# 1. State the Hypotheses
# -------------------------------
# H0 (Null Hypothesis): There is no association between device type and customer satisfaction.
# H1 (Alternative Hypothesis): There is an association between device type and customer satisfaction.

# -------------------------------
# 2. Observed Frequencies Table
# -------------------------------
# Satisfaction       | Smart Thermostat | Smart Light
# ---------------------------------------------------
# Very Satisfied     | 50               | 70
# Satisfied          | 80               | 100
# Neutral            | 60               | 90
# Unsatisfied        | 30               | 50
# Very Unsatisfied   | 20               | 50

observed = np.array([
    [50, 70],
    [80, 100],
    [60, 90],
    [30, 50],
    [20, 50]
])

# -------------------------------
# 3. Compute Chi-Square Statistic
# -------------------------------
chi2_stat, p_value, dof, expected = stats.chi2_contingency(observed)

# -------------------------------
# 4. Determine Critical Value
# -------------------------------
alpha = 0.05
critical_value = stats.chi2.ppf(q=1 - alpha, df=dof)

# -------------------------------
# 5. Make a Decision
# -------------------------------
print("Chi-Square Test for Independence\n")
print("Observed Frequencies:\n", observed)
print("\nExpected Frequencies:\n", np.round(expected, 2))
print(f"\nDegrees of Freedom: {dof}")
print(f"Significance Level (alpha): {alpha}")
print(f"Chi-Square Statistic: {chi2_stat:.2f}")
print(f"Critical Value: {critical_value:.2f}")
print(f"P-Value: {p_value:.4f}")

# Decision
if chi2_stat > critical_value:
    print("\nConclusion: Reject the null hypothesis.")
    print("There IS a significant association between device type and customer satisfaction.")
else:
    print("\nConclusion: Fail to reject the null hypothesis.")
    print("There is NO significant association between device type and customer satisfaction.")


Chi-Square Test for Independence

Observed Frequencies:
 [[ 50  70]
 [ 80 100]
 [ 60  90]
 [ 30  50]
 [ 20  50]]

Expected Frequencies:
 [[ 48.  72.]
 [ 72. 108.]
 [ 60.  90.]
 [ 32.  48.]
 [ 28.  42.]]

Degrees of Freedom: 4
Significance Level (alpha): 0.05
Chi-Square Statistic: 5.64
Critical Value: 9.49
P-Value: 0.2278

Conclusion: Fail to reject the null hypothesis.
There is NO significant association between device type and customer satisfaction.


In [3]:
import math
from scipy.stats import norm

# Given data
sample_mean = 3050
theoretical_mean = 1000 + 5 * 600  # = 4000
sigma = 5 * 25  # = 125
n = 25

# Calculate Z-test statistic
z = (sample_mean - theoretical_mean) / (sigma / math.sqrt(n))
print(f"Z-Test Statistic: {z:.2f}")

# Critical value for one-tailed test at α = 0.05
alpha = 0.05
z_critical = norm.ppf(1 - alpha)
print(f"Critical Value (Zα): {z_critical:.2f}")

# Decision
if z > z_critical:
    print("Reject the null hypothesis: There is evidence that weekly costs have increased.")
else:
    print("Fail to reject the null hypothesis: No evidence that weekly costs have increased.")


Z-Test Statistic: -38.00
Critical Value (Zα): 1.64
Fail to reject the null hypothesis: No evidence that weekly costs have increased.
